apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envforge.fullname" . }}-config
  labels:
    app: {{ include "envforge.fullname" . }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
